### ISSUE TITLE
懒人包脚本启动异常

### ISSUE THREAD

**Issue by Mylszd** [wenda-LLM/wenda#299]
运行每个bat文件都会出现如下错误
ValueError: invalid literal for int() with base 10: '\x00'

系统版本：windows server 2019 Standard
显卡：3090

检测到新版集成环境，使用内置Python解释器
Traceback (most recent call last):
  File "E:\project\wenda\wd-git_5.18\wenda\plugins\gen_data_qdrant.py", line 6, in <module>
    from sentence_transformers import SentenceTransformer
  File "E:\project\wenda\wd-git_5.18\wenda\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\sentence_transformers\__init__.py", line 3, in <module>
    from .datasets import SentencesDataset, ParallelSentencesDataset
  File "E:\project\wenda\wd-git_5.18\wenda\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\sentence_transformers\datasets\__init__.py", line 3, in <module>
    from .ParallelSentencesDataset import ParallelSentencesDataset
  File "E:\project\wenda\wd-git_5.18\wenda\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\sentence_transformers\datasets\ParallelSentencesDataset.py", line 4, in <module>
    from .. import SentenceTransformer
  File "E:\project\wenda\wd-git_5.18\wenda\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\sentence_transformers\SentenceTransformer.py", line 11, in <module>
    import transformers
  File "E:\project\wenda\wd-git_5.18\wenda\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\transformers\__init__.py", line 30, in <module>
    from . import dependency_versions_check
  File "E:\project\wenda\wd-git_5.18\wenda\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\transformers\dependency_versions_check.py", line 17, in <module>
    from .utils.versions import require_version, require_version_core
  File "E:\project\wenda\wd-git_5.18\wenda\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\transformers\utils\__init__.py", line 60, in <module>
    from .hub import (
  File "E:\project\wenda\wd-git_5.18\wenda\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\transformers\utils\hub.py", line 1087, in <module>
    cache_version = int(f.read())
                    ^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '\x00'
Press any key to continue . . .

**Comment by l15y** [comment]
模型没下好？

**Comment by l15y** [comment]
https://github.com/huggingface/transformers/issues/22412
尝试更新下这个库？pip 终端里

**Comment by Mylszd** [comment]
更新到4.29.1 和 4.29.1版本出现了这个问题 https://github.com/wenda-LLM/wenda/issues/262 ，有比较合适的transformers版本么？

**Comment by l15y** [comment]
我记得git版本是好的

**Comment by Mylszd** [comment]
使用5.10的版本可以正常运行，但是现在有个问题，就是在加载比较大的知识库的时候155K的txt，会导致windows重启，观察显存占用了3个G，没有占满也；加载小的1-2K的txt就不会重启，这个是什么问题呢,是我电脑的原因吗?(一张3090显卡同时显示和运行程序)

**Comment by sjzy137** [comment]
我也出现了同样的问题：ValueError: invalid literal for int() with base 10: '\x00'
而且更新显示：网络连接失败，请过一段时间重试
请问如何解决？
