### ISSUE TITLE
生成知识库脚本报错

### ISSUE THREAD

**Issue by philipyao** [wenda-LLM/wenda#318]
windows 平台，conda python 3.8.16 环境，手动生成知识库出错如下（另外 environment.bat有语法错误，我手动执行的py脚本）：

>python plugins\gen_data_st.py

Traceback (most recent call last):
  File "plugins\gen_data_st.py", line 4, in <module>
    from langchain.text_splitter import CharacterTextSplitter
  File "C:\Users\win10\anaconda3\envs\condaenv2\lib\site-packages\langchain\__init__.py", line 6, in <module>
    from langchain.agents import MRKLChain, ReActChain, SelfAskWithSearchChain
  File "C:\Users\win10\anaconda3\envs\condaenv2\lib\site-packages\langchain\agents\__init__.py", line 2, in <module>
    from langchain.agents.agent import (
  File "C:\Users\win10\anaconda3\envs\condaenv2\lib\site-packages\langchain\agents\agent.py", line 16, in <module>
    from langchain.agents.tools import InvalidTool
  File "C:\Users\win10\anaconda3\envs\condaenv2\lib\site-packages\langchain\agents\tools.py", line 8, in <module>
    from langchain.tools.base import BaseTool, Tool, tool
  File "C:\Users\win10\anaconda3\envs\condaenv2\lib\site-packages\langchain\tools\__init__.py", line 42, in <module>
    from langchain.tools.vectorstore.tool import (
  File "C:\Users\win10\anaconda3\envs\condaenv2\lib\site-packages\langchain\tools\vectorstore\tool.py", line 13, in <module>
    from langchain.chains import RetrievalQA, RetrievalQAWithSourcesChain
  File "C:\Users\win10\anaconda3\envs\condaenv2\lib\site-packages\langchain\chains\__init__.py", line 2, in <module>
    from langchain.chains.api.base import APIChain
  File "C:\Users\win10\anaconda3\envs\condaenv2\lib\site-packages\langchain\chains\api\base.py", line 13, in <module>
    from langchain.chains.api.prompt import API_RESPONSE_PROMPT, API_URL_PROMPT
  File "C:\Users\win10\anaconda3\envs\condaenv2\lib\site-packages\langchain\chains\api\prompt.py", line 2, in <module>
    from langchain.prompts.prompt import PromptTemplate
  File "C:\Users\win10\anaconda3\envs\condaenv2\lib\site-packages\langchain\prompts\__init__.py", line 3, in <module>
    from langchain.prompts.chat import (
  File "C:\Users\win10\anaconda3\envs\condaenv2\lib\site-packages\langchain\prompts\chat.py", line 10, in <module>
    from langchain.memory.buffer import get_buffer_string
  File "C:\Users\win10\anaconda3\envs\condaenv2\lib\site-packages\langchain\memory\__init__.py", line 28, in <module>
    from langchain.memory.vectorstore import VectorStoreRetrieverMemory
  File "C:\Users\win10\anaconda3\envs\condaenv2\lib\site-packages\langchain\memory\vectorstore.py", line 10, in <module>
    from langchain.vectorstores.base import VectorStoreRetriever
  File "C:\Users\win10\anaconda3\envs\condaenv2\lib\site-packages\langchain\vectorstores\__init__.py", line 2, in <module>
    from langchain.vectorstores.analyticdb import AnalyticDB
  File "C:\Users\win10\anaconda3\envs\condaenv2\lib\site-packages\langchain\vectorstores\analyticdb.py", line 16, in <module>
    from langchain.embeddings.base import Embeddings
  File "C:\Users\win10\anaconda3\envs\condaenv2\lib\site-packages\langchain\embeddings\__init__.py", line 19, in <module>
    from langchain.embeddings.openai import OpenAIEmbeddings
  File "C:\Users\win10\anaconda3\envs\condaenv2\lib\site-packages\langchain\embeddings\openai.py", line 67, in <module>
    class OpenAIEmbeddings(BaseModel, Embeddings):
  File "pydantic\main.py", line 197, in pydantic.main.ModelMetaclass.__new__
  File "pydantic\fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic\fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic\fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic\fields.py", line 663, in pydantic.fields.ModelField._type_analysis
  File "pydantic\fields.py", line 808, in pydantic.fields.ModelField._create_sub_type
  File "pydantic\fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic\fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic\fields.py", line 668, in pydantic.fields.ModelField._type_analysis
  File "C:\Users\win10\anaconda3\envs\condaenv2\lib\typing.py", line 774, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class

**Comment by philipyao** [comment]
自己更新一下，供碰到环境问题的朋友参考：
# conda 安装python 3.9（3.8、3.10 都会报奇奇怪怪的错）
conda create --name envwenda python=3.9
# 安装 cuda 版本的 pytorch，版本也要合适
conda install pytorch==2.0.0 torchvision==0.15.0 torchaudio==2.0.0 pytorch-cuda=11.8 -c pytorch -c nvidia
# 项目的 environment.bat 脚本格式有错，不能运行，但是这个脚本没什么卵用，如果要生产 rtst 知识库直接 
python plugins\gen_data_st.py
# 同样 run_GLM6B.bat 因为调用 environment.bat  会报错，直接 
python wenda.py -t glm6b

**Comment by l15y** [comment]
`项目的environment.bat脚本格式有错误，不能运行，但是这个脚本没有什么用，如果要生产首先知识库直接连接`
wsl下git会导致错误格式

**Comment by YaoQ** [comment]
在Ubuntu环境下，也遇到类似的问题，除了升级torch=2.0.0之外，还参考了：[pydantic issue](https://github.com/pydantic/pydantic/issues/545)
即，强制安装版本：
python -m pip install  typing-extensions==4.5.0
