### ISSUE TITLE
windows下，Could not find module 'C:\Users\WindowSide\.cache\huggingface\modules\transformers_modules\local\quantization_kernels_parallel.so' (or one of its dependencies).

### ISSUE THREAD

**Issue by wantRP** [wenda-LLM/wenda#354]
```
No compiled kernel found.
Compiling kernels : C:\Users\WindowSide\.cache\huggingface\modules\transformers_modules\local\quantization_kernels_parallel.c
Compiling gcc -O3 -fPIC -pthread -fopenmp -std=c99 C:\Users\WindowSide\.cache\huggingface\modules\transformers_modules\local\quantization_kernels_parallel.c -shared -o C:\Users\WindowSide\.cache\huggingface\modules\transformers_modules\local\quantization_kernels_parallel.so
Load parallel cpu kernel failed, using default cpu kernel code:
Traceback (most recent call last):
  File "C:\Users\WindowSide/.cache\huggingface\modules\transformers_modules\local\quantization.py", line 156, in __init__
    kernels = ctypes.cdll.LoadLibrary(kernel_file)
  File "C:\Users\WindowSide\anaconda3\envs\wenda\lib\ctypes\__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\WindowSide\anaconda3\envs\wenda\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\Users\WindowSide\.cache\huggingface\modules\transformers_modules\local\quantization_kernels_parallel.so' (or one of its dependencies). Try using the full path with constructor syntax.

Compiling gcc -O3 -fPIC -std=c99 C:\Users\WindowSide\.cache\huggingface\modules\transformers_modules\local\quantization_kernels.c -shared -o C:\Users\WindowSide\.cache\huggingface\modules\transformers_modules\local\quantization_kernels.so
Load kernel : C:\Users\WindowSide\.cache\huggingface\modules\transformers_modules\local\quantization_kernels.so
Using quantization cache
Applying quantization to glm layers
```

**Comment by l15y** [comment]
如果不会装，就不要用cpu量化或推理
