### ISSUE TITLE
今天更新后出现这个错误

### ISSUE THREAD

**Issue by hopeforus** [wenda-LLM/wenda#366]
(wenda) hope@hope-08:~/work/wenda$ python wenda.py
Traceback (most recent call last):
  File "/home/hope/work/wenda/wenda.py", line 18, in <module>
    from plugins.common import error_helper, error_print, success_print
  File "/home/hope/work/wenda/plugins/common.py", line 140
    <<<<<<< Updated upstream
    ^
SyntaxError: invalid syntax

**Comment by hopeforus** [comment]
是文件更新出问题了，已经解决！
