### ISSUE TITLE
安装一切正常，但是运行中出错（前几条回答没问题，突然出错）

### ISSUE THREAD

**Issue by shadowbox-cash** [wenda-LLM/wenda#389]
出错信息如下：
Traceback (most recent call last):
  File "/root/miniconda3/envs/myenv/lib/python3.9/site-packages/bottle.py", line 876, in _handle
    return route.call(**args)
  File "/root/miniconda3/envs/myenv/lib/python3.9/site-packages/bottle.py", line 1759, in wrapper
    rv = callback(*a, **ka)
  File "/root/wenda/wenda.py", line 154, in api_find
    return json.dumps(zhishiku.find(prompt, int(step)))
  File "/root/wenda/plugins/zhishiku.py", line 24, in find
    result += item['zsk'].find(s, step)[:item['count']]
  File "/root/wenda/plugins/zhishiku_calc.py", line 4, in find
    return [{'title': "[闻达计算器]()", 'content':calc+"="+str(eval(calc))} for calc in calc_pattern.findall(search_query)]
  File "/root/wenda/plugins/zhishiku_calc.py", line 4, in <listcomp>
    return [{'title': "[闻达计算器]()", 'content':calc+"="+str(eval(calc))} for calc in calc_pattern.findall(search_query)]
  File "<string>", line 1
    /
    ^
SyntaxError: unexpected EOF while parsing

**Comment by l15y** [comment]
输入了什么内容？

**Comment by TommyTunaToro** [comment]
> 出错信息如下： Traceback (most recent call last): File "/root/miniconda3/envs/myenv/lib/python3.9/site-packages/bottle.py", line 876, in _handle return route.call(**args) File "/root/miniconda3/envs/myenv/lib/python3.9/site-packages/bottle.py", line 1759, in wrapper rv = callback(*a, **ka) File "/root/wenda/wenda.py", line 154, in api_find return json.dumps(zhishiku.find(prompt, int(step))) File "/root/wenda/plugins/zhishiku.py", line 24, in find result += item['zsk'].find(s, step)[:item['count']] File "/root/wenda/plugins/zhishiku_calc.py", line 4, in find return [{'title': "闻达计算器", 'content':calc+"="+str(eval(calc))} for calc in calc_pattern.findall(search_query)] File "/root/wenda/plugins/zhishiku_calc.py", line 4, in return [{'title': "闻达计算器", 'content':calc+"="+str(eval(calc))} for calc in calc_pattern.findall(search_query)] File "", line 1 / ^ SyntaxError: unexpected EOF while parsing

我遇到了相同的问题，目前已知的是，在启用知识库之后，问题中只要包含罗马数字就会调用到zhishiku_calc.py这个plugin功能。我正在读源代码准备手动修复，成功了会分享你。原作者的目的应该是希望添加类似Tools之类的功能，禁止掉的话可能就无法算算术了。
