### ISSUE TITLE
mbedding加载失败，请下载语义知识库计算模型

### ISSUE THREAD

**Issue by lhtpluto** [wenda-LLM/wenda#406]
mbedding加载失败，请下载语义知识库计算模型

config.yml 中
glm6b: 
     path: "D:\\temp ai\\wenda\\ChatGLM2-6B"

**Desktop (please complete the following information):**
 - OS: [e.g. windows]
 - Browser [e.g. chrome,]

(D:\temp ai\wenda\env) D:\temp ai\wenda>python wenda.py -t glm6b
Namespace(Config='config.yml', LLM_Type='glm6b', Logging=None, Port=None)
library:
  count: 5
  step: 2
  strategy: calc:2 rtst:2 agents:0
librarys:
  bing:
    count: 5
  bingsite:
    count: 5
    site: www.12371.cn
  fess:
    count: 1
    fess_host: 127.0.0.1:8080
  kg:
    count: 5
    graph_host: ''
    knowledge_path: ''
    model_path: ''
  qdrant:
    batch_size: 32
    collection: qa_collection
    count: 3
    device: cpu
    model_path: model/m3e-base
    overlap: 0
    path: txt
    qdrant_path: memory/q
    similarity_threshold: 0.8
    size: 20
  remote:
    host: http://127.0.0.1:17860/api/find
  rtst:
    count: 3
    device: cuda
    model_path: model/m3e-base
    overlap: 0
    size: 20
llm:
  path: D:\temp ai\wenda\ChatGLM2-6B
  strategy: cuda fp16
llm_type: glm6b
logging: false
port: 17860

Traceback (most recent call last):
  File "wenda.py", line 355, in <module>
    app.mount("/txt/", StaticFiles(directory="txt"), name="txt")
  File "D:\temp ai\wenda\env\lib\site-packages\starlette\staticfiles.py", line 57, in __init__
    raise RuntimeError(f"Directory '{directory}' does not exist")
RuntimeError: Directory 'txt' does not exist
[['cuda', 'fp16']]
Loading checkpoint shards:  14%|████████▏                                                | 1/7 [00:00<00:05,  1.05it/s]embedding加载失败，请下载语义知识库计算模型
查看： https://github.com/l15y/wenda#st%E6%A8%A1%E5%BC%8F
2023-06-26 13:27:46.242 | ERROR    | __main__:load_zsk:69 - ('Connection aborted.', ConnectionResetError(10054, '远程主
机强迫关闭了一个现有的连接。', None, 10054, None))

担心文件夹格式写错，直接在根目录下建立模型文件
glm6b: 
     path: "ChatGLM2-6B"

都一样的错误

llm:
  path: ChatGLM2-6B
  strategy: cuda fp16
llm_type: glm6b
logging: false
port: 17860

Traceback (most recent call last):
  File "wenda.py", line 355, in <module>
    app.mount("/txt/", StaticFiles(directory="txt"), name="txt")
  File "D:\temp ai\wenda\env\lib\site-packages\starlette\staticfiles.py", line 57, in __init__
    raise RuntimeError(f"Directory '{directory}' does not exist")
RuntimeError: Directory 'txt' does not exist
[['cuda', 'fp16']]
Loading checkpoint shards:  14%|████████▏                                                | 1/7 [00:00<00:05,  1.02it/s]embedding加载失败，请下载语义知识库计算模型
查看： https://github.com/l15y/wenda#st%E6%A8%A1%E5%BC%8F

**Comment by lhtpluto** [comment]
应该是缺这个
rtst: 
     count: 3
     #最大抽取数量
   #   backend: Annoy
     size: 20
     #分块大小"
     overlap: 0
     #分块重叠长度
     model_path: "model/m3e-base"
     #向量模型存储路径
     device: cuda
     #embedding运行设备

**Comment by lhtpluto** [comment]
(D:\temp ai\wenda\env) D:\temp ai\wenda>python.exe wenda.py -t glm6b
Namespace(Config='config.yml', LLM_Type='glm6b', Logging=None, Port=None)
library:
  count: 5
  step: 2
  strategy: calc:2 rtst:2 agents:0
librarys:
  bing:
    count: 5
  bingsite:
    count: 5
    site: www.12371.cn
  fess:
    count: 1
    fess_host: 127.0.0.1:8080
  kg:
    count: 5
    graph_host: ''
    knowledge_path: ''
    model_path: ''
  qdrant:
    batch_size: 32
    collection: qa_collection
    count: 3
    device: cpu
    model_path: model/m3e-base
    overlap: 0
    path: txt
    qdrant_path: memory/q
    similarity_threshold: 0.8
    size: 20
  remote:
    host: http://127.0.0.1:17860/api/find
  rtst:
    count: 3
    device: cpu
    model_path: m3e-base
    overlap: 0
    size: 20
llm:
  path: chatglm-6b
  strategy: cuda fp16
llm_type: glm6b
logging: false
port: 17860

Traceback (most recent call last):
  File "wenda.py", line 355, in <module>
    app.mount("/txt/", StaticFiles(directory="txt"), name="txt")
  File "D:\temp ai\wenda\env\lib\site-packages\starlette\staticfiles.py", line 57, in __init__
    raise RuntimeError(f"Directory '{directory}' does not exist")
RuntimeError: Directory 'txt' does not exist
[['cuda', 'fp16']]
Loading checkpoint shards:  12%|███████▏                                                 | 1/8 [00:00<00:06,  1.16it/s]No sentence-transformers model found with name m3e-base. Creating a new one with MEAN pooling.
知识库加载完成
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 8/8 [00:06<00:00,  1.23it/s]
模型加载完成

(D:\temp ai\wenda\env) D:\temp ai\wenda>
