### ISSUE TITLE
如何运行？

### ISSUE THREAD

**Issue by Lufffya** [wenda-LLM/wenda#411]
直接执行对应模型的脚本，还是python wenda.py？

**Comment by Lufffya** [comment]
```
(wenda) root@ubuntu103:/home/zxc/wenda# python wenda.py -t glm6b
Namespace(Config='config.yml', Port=None, Logging=None, LLM_Type='glm6b')
library:
  count: 5
  step: 2
  strategy: calc:2 rtst:2 agents:0
librarys:
  bing:
    count: 5
  bingsite:
    count: 5
    site: www.12371.cn
  fess:
    count: 1
    fess_host: 127.0.0.1:8080
  kg:
    count: 5
    graph_host: ''
    knowledge_path: ''
    model_path: ''
  qdrant:
    batch_size: 32
    collection: qa_collection
    count: 3
    device: cpu
    model_path: model/m3e-base
    overlap: 0
    path: txt
    qdrant_path: memory/q
    similarity_threshold: 0.8
    size: 20
  remote:
    host: http://127.0.0.1:17860/api/find
  rtst:
    count: 3
    device: cuda
    model_path: model/m3e-base
    overlap: 0
    size: 20
llm:
  path: /home/zxc/models/chatglm2-6b
  strategy: cuda fp16
llm_type: glm6b
logging: false
port: 17860

Traceback (most recent call last):
  File "/home/zxc/wenda/wenda.py", line 355, in <module>
    app.mount("/txt/", StaticFiles(directory="txt"), name="txt")
  File "/root/anaconda3/envs/wenda/lib/python3.10/site-packages/starlette/staticfiles.py", line 57, in __init__
    raise RuntimeError(f"Directory '{directory}' does not exist")
RuntimeError: Directory 'txt' does not exist
[['cuda', 'fp16']]
2023-06-28 11:44:50.752 | ERROR    | __main__:load_zsk:69 - can't register atexit after shutdown
Traceback (most recent call last):

  File "/root/anaconda3/envs/wenda/lib/python3.10/threading.py", line 966, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fee960f60e0>
    └ <Thread(Thread-2 (load_zsk), started 140658058716736)>
  File "/root/anaconda3/envs/wenda/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fee960f5e10>
    └ <Thread(Thread-2 (load_zsk), started 140658058716736)>
  File "/root/anaconda3/envs/wenda/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-2 (load_zsk), started 140658058716736)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-2 (load_zsk), started 140658058716736)>
    │    └ <function load_zsk at 0x7fed8253c430>
    └ <Thread(Thread-2 (load_zsk), started 140658058716736)>

> File "/home/zxc/wenda/wenda.py", line 65, in load_zsk
    import plugins.zhishiku as zsk

  File "/home/zxc/wenda/plugins/zhishiku.py", line 15, in <module>
    zhishiku = import_module('plugins.zhishiku_'+item[0])
               │                                 └ ['rtst', '2']
               └ <function import_module at 0x7fee95c16e60>

  File "/root/anaconda3/envs/wenda/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           │          │           │    │        │        └ 0
           │          │           │    │        └ None
           │          │           │    └ 0
           │          │           └ 'plugins.zhishiku_rtst'
           │          └ <function _gcd_import at 0x7fee9652f400>
           └ <module '_frozen_importlib' (frozen)>

  File "/home/zxc/wenda/plugins/zhishiku_rtst.py", line 3, in <module>
    import sentence_transformers

  File "/root/anaconda3/envs/wenda/lib/python3.10/site-packages/sentence_transformers/__init__.py", line 3, in <module>
    from .datasets import SentencesDataset, ParallelSentencesDataset
  File "/root/anaconda3/envs/wenda/lib/python3.10/site-packages/sentence_transformers/datasets/__init__.py", line 1, in <module>
    from .DenoisingAutoEncoderDataset import DenoisingAutoEncoderDataset
  File "/root/anaconda3/envs/wenda/lib/python3.10/site-packages/sentence_transformers/datasets/DenoisingAutoEncoderDataset.py", line 5, in <module>
    import nltk
  File "/root/anaconda3/envs/wenda/lib/python3.10/site-packages/nltk/__init__.py", line 146, in <module>
    from nltk.chunk import *
  File "/root/anaconda3/envs/wenda/lib/python3.10/site-packages/nltk/chunk/__init__.py", line 155, in <module>
    from nltk.chunk.api import ChunkParserI
  File "/root/anaconda3/envs/wenda/lib/python3.10/site-packages/nltk/chunk/api.py", line 13, in <module>
    from nltk.chunk.util import ChunkScore
  File "/root/anaconda3/envs/wenda/lib/python3.10/site-packages/nltk/chunk/util.py", line 12, in <module>
    from nltk.tag.mapping import map_tag
  File "/root/anaconda3/envs/wenda/lib/python3.10/site-packages/nltk/tag/__init__.py", line 70, in <module>
    from nltk.tag.sequential import (
  File "/root/anaconda3/envs/wenda/lib/python3.10/site-packages/nltk/tag/sequential.py", line 26, in <module>
    from nltk.classify import NaiveBayesClassifier
  File "/root/anaconda3/envs/wenda/lib/python3.10/site-packages/nltk/classify/__init__.py", line 97, in <module>
    from nltk.classify.scikitlearn import SklearnClassifier
  File "/root/anaconda3/envs/wenda/lib/python3.10/site-packages/nltk/classify/scikitlearn.py", line 38, in <module>
    from sklearn.feature_extraction import DictVectorizer
  File "/root/anaconda3/envs/wenda/lib/python3.10/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/root/anaconda3/envs/wenda/lib/python3.10/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/root/anaconda3/envs/wenda/lib/python3.10/site-packages/sklearn/utils/__init__.py", line 21, in <module>
    from . import _joblib
  File "/root/anaconda3/envs/wenda/lib/python3.10/site-packages/sklearn/utils/_joblib.py", line 7, in <module>
    import joblib
  File "/root/anaconda3/envs/wenda/lib/python3.10/site-packages/joblib/__init__.py", line 120, in <module>
    from .parallel import Parallel
  File "/root/anaconda3/envs/wenda/lib/python3.10/site-packages/joblib/parallel.py", line 26, in <module>
    from ._parallel_backends import (FallbackToBackend, MultiprocessingBackend,
  File "/root/anaconda3/envs/wenda/lib/python3.10/site-packages/joblib/_parallel_backends.py", line 17, in <module>
    from .pool import MemmappingPool
  File "/root/anaconda3/envs/wenda/lib/python3.10/site-packages/joblib/pool.py", line 31, in <module>
    from ._memmapping_reducer import get_memmapping_reducers
  File "/root/anaconda3/envs/wenda/lib/python3.10/site-packages/joblib/_memmapping_reducer.py", line 37, in <module>
    from .externals.loky.backend import resource_tracker
  File "/root/anaconda3/envs/wenda/lib/python3.10/site-packages/joblib/externals/loky/__init__.py", line 20, in <module>
    from .reusable_executor import get_reusable_executor
  File "/root/anaconda3/envs/wenda/lib/python3.10/site-packages/joblib/externals/loky/reusable_executor.py", line 11, in <module>
    from .process_executor import ProcessPoolExecutor, EXTRA_QUEUED_CALLS
  File "/root/anaconda3/envs/wenda/lib/python3.10/site-packages/joblib/externals/loky/process_executor.py", line 77, in <module>
    from concurrent.futures.process import BrokenProcessPool as _BPPException
  File "/root/anaconda3/envs/wenda/lib/python3.10/concurrent/futures/process.py", line 101, in <module>
    threading._register_atexit(_python_exit)
    │         │                └ <function _python_exit at 0x7fec982752d0>
    │         └ <function _register_atexit at 0x7fee960f71c0>
    └ <module 'threading' from '/root/anaconda3/envs/wenda/lib/python3.10/threading.py'>
  File "/root/anaconda3/envs/wenda/lib/python3.10/threading.py", line 1484, in _register_atexit
    raise RuntimeError("can't register atexit after shutdown")

RuntimeError: can't register atexit after shutdown
知识库加载失败，请阅读说明
查看： https://github.com/l15y/wenda#%E7%9F%A5%E8%AF%86%E5%BA%93
Exception in thread Thread-2 (load_zsk):
Traceback (most recent call last):
  File "/root/anaconda3/envs/wenda/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/root/anaconda3/envs/wenda/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/home/zxc/wenda/wenda.py", line 72, in load_zsk
    raise e
  File "/home/zxc/wenda/wenda.py", line 65, in load_zsk
    import plugins.zhishiku as zsk
  File "/home/zxc/wenda/plugins/zhishiku.py", line 15, in <module>
    zhishiku = import_module('plugins.zhishiku_'+item[0])
  File "/root/anaconda3/envs/wenda/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/zxc/wenda/plugins/zhishiku_rtst.py", line 3, in <module>
    import sentence_transformers
  File "/root/anaconda3/envs/wenda/lib/python3.10/site-packages/sentence_transformers/__init__.py", line 3, in <module>
    from .datasets import SentencesDataset, ParallelSentencesDataset
  File "/root/anaconda3/envs/wenda/lib/python3.10/site-packages/sentence_transformers/datasets/__init__.py", line 1, in <module>
    from .DenoisingAutoEncoderDataset import DenoisingAutoEncoderDataset
  File "/root/anaconda3/envs/wenda/lib/python3.10/site-packages/sentence_transformers/datasets/DenoisingAutoEncoderDataset.py", line 5, in <module>
    import nltk
  File "/root/anaconda3/envs/wenda/lib/python3.10/site-packages/nltk/__init__.py", line 146, in <module>
    from nltk.chunk import *
  File "/root/anaconda3/envs/wenda/lib/python3.10/site-packages/nltk/chunk/__init__.py", line 155, in <module>
    from nltk.chunk.api import ChunkParserI
  File "/root/anaconda3/envs/wenda/lib/python3.10/site-packages/nltk/chunk/api.py", line 13, in <module>
    from nltk.chunk.util import ChunkScore
  File "/root/anaconda3/envs/wenda/lib/python3.10/site-packages/nltk/chunk/util.py", line 12, in <module>
    from nltk.tag.mapping import map_tag
  File "/root/anaconda3/envs/wenda/lib/python3.10/site-packages/nltk/tag/__init__.py", line 70, in <module>
    from nltk.tag.sequential import (
  File "/root/anaconda3/envs/wenda/lib/python3.10/site-packages/nltk/tag/sequential.py", line 26, in <module>
    from nltk.classify import NaiveBayesClassifier
  File "/root/anaconda3/envs/wenda/lib/python3.10/site-packages/nltk/classify/__init__.py", line 97, in <module>
    from nltk.classify.scikitlearn import SklearnClassifier
  File "/root/anaconda3/envs/wenda/lib/python3.10/site-packages/nltk/classify/scikitlearn.py", line 38, in <module>
    from sklearn.feature_extraction import DictVectorizer
  File "/root/anaconda3/envs/wenda/lib/python3.10/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/root/anaconda3/envs/wenda/lib/python3.10/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/root/anaconda3/envs/wenda/lib/python3.10/site-packages/sklearn/utils/__init__.py", line 21, in <module>
    from . import _joblib
  File "/root/anaconda3/envs/wenda/lib/python3.10/site-packages/sklearn/utils/_joblib.py", line 7, in <module>
    import joblib
  File "/root/anaconda3/envs/wenda/lib/python3.10/site-packages/joblib/__init__.py", line 120, in <module>
    from .parallel import Parallel
  File "/root/anaconda3/envs/wenda/lib/python3.10/site-packages/joblib/parallel.py", line 26, in <module>
    from ._parallel_backends import (FallbackToBackend, MultiprocessingBackend,
  File "/root/anaconda3/envs/wenda/lib/python3.10/site-packages/joblib/_parallel_backends.py", line 17, in <module>
    from .pool import MemmappingPool
  File "/root/anaconda3/envs/wenda/lib/python3.10/site-packages/joblib/pool.py", line 31, in <module>
    from ._memmapping_reducer import get_memmapping_reducers
  File "/root/anaconda3/envs/wenda/lib/python3.10/site-packages/joblib/_memmapping_reducer.py", line 37, in <module>
    from .externals.loky.backend import resource_tracker
  File "/root/anaconda3/envs/wenda/lib/python3.10/site-packages/joblib/externals/loky/__init__.py", line 20, in <module>
    from .reusable_executor import get_reusable_executor
  File "/root/anaconda3/envs/wenda/lib/python3.10/site-packages/joblib/externals/loky/reusable_executor.py", line 11, in <module>
    from .process_executor import ProcessPoolExecutor, EXTRA_QUEUED_CALLS
  File "/root/anaconda3/envs/wenda/lib/python3.10/site-packages/joblib/externals/loky/process_executor.py", line 77, in <module>
    from concurrent.futures.process import BrokenProcessPool as _BPPException
  File "/root/anaconda3/envs/wenda/lib/python3.10/concurrent/futures/process.py", line 101, in <module>
    threading._register_atexit(_python_exit)
  File "/root/anaconda3/envs/wenda/lib/python3.10/threading.py", line 1484, in _register_atexit
    raise RuntimeError("can't register atexit after shutdown")
RuntimeError: can't register atexit after shutdown
```

这个错误怎么解决呢

**Comment by cgisky1980** [comment]
建立一个txt文件夹

**Comment by heiheiheibj** [comment]
raise RuntimeError(f"Directory '{directory}' does not exist")
在wenda目录下建一个名为txt的空目录就可以了
