### ISSUE TITLE
ModuleNotFoundError: No module named 'transformers_modules.model/chatglm2-6b-int4' No sentence-transformers model found with name model/m3e-base. Creating a new one with MEAN pooling.

### ISSUE THREAD

**Issue by wu5shen** [wenda-LLM/wenda#417]
下载的懒人包，出现这种情况然后一直没反应，是什么问题？？
[['cuda', 'fp16']]
Exception in thread Thread-1 (load_model):
Traceback (most recent call last):
  File "F:\AI\GLM\WD\WPy64-31110\python-3.11.1.amd64\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "F:\AI\GLM\WD\WPy64-31110\python-3.11.1.amd64\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "F:\AI\GLM\WD\wenda\wenda.py", line 53, in load_model
    LLM.load_model()
  File "F:\AI\GLM\WD\wenda\llms\llm_glm6b.py", line 68, in load_model
    tokenizer = AutoTokenizer.from_pretrained(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\GLM\WD\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\transformers\models\auto\tokenization_auto.py", line 676, in from_pretrained
    tokenizer_class = get_class_from_dynamic_module(class_ref, pretrained_model_name_or_path, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\GLM\WD\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\transformers\dynamic_module_utils.py", line 443, in get_class_from_dynamic_module
    return get_class_in_module(class_name, final_module.replace(".py", ""))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\GLM\WD\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\transformers\dynamic_module_utils.py", line 164, in get_class_in_module
    module = importlib.import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\GLM\WD\WPy64-31110\python-3.11.1.amd64\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1128, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'transformers_modules.model/chatglm2-6b-int4'
No sentence-transformers model found with name model/m3e-base. Creating a new one with MEAN pooling.
知识库加载完成

**Comment by serfan** [comment]
昨天第一次运行的时候遇到类似问题，好像是修改了配置文件导致的，后来删除了配置文件重新初始化配置，就没发现类似问题了。
