### ISSUE TITLE
错误 'NoneType' object has no attribute 'int4WeightExtractionHalf'

### ISSUE THREAD

**Issue by wu5shen** [wenda-LLM/wenda#419]
[['cuda', 'fp16']]
No sentence-transformers model found with name model/m3e-base. Creating a new one with MEAN pooling.
知识库加载完成
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\wu5shen/.cache\huggingface\modules\transformers_modules\chatglm-6b-int4\quantization.py", line 19, in <module>
    from cpm_kernels.kernels.base import LazyKernelCModule, KernelFunction, round_up
  File "I:\AI\Chart GLM\main\wenda\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\cpm_kernels\__init__.py", line 1, in <module>
    from . import library
  File "I:\AI\Chart GLM\main\wenda\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\cpm_kernels\library\__init__.py", line 2, in <module>
    from . import cuda
  File "I:\AI\Chart GLM\main\wenda\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\cpm_kernels\library\cuda.py", line 7, in <module>
    cuda = Lib.from_lib("cuda", ctypes.WinDLL("nvcuda.dll"))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\AI\Chart GLM\main\wenda\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\cpm_kernels\library\base.py", line 63, in from_lib
    ret = Lib(name)
          ^^^^^^^^^
  File "I:\AI\Chart GLM\main\wenda\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\cpm_kernels\library\base.py", line 45, in __init__
    lib_path = windows_find_lib(self.__name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\AI\Chart GLM\main\wenda\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\cpm_kernels\library\base.py", line 39, in windows_find_lib
    return lookup_dll(lib_name)
           ^^^^^^^^^^^^^^^^^^^^
  File "I:\AI\Chart GLM\main\wenda\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\cpm_kernels\library\base.py", line 16, in lookup_dll
    for name in os.listdir(path):
                ^^^^^^^^^^^^^^^^
NotADirectoryError: [WinError 267] 目录名称无效。: 'C:\\Users\\wu5shen\\AppData\\Local\\Programs\\Python\\Python310\\python.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "I:\AI\Chart GLM\main\wenda\WPy64-31110\python-3.11.1.amd64\Lib\logging\__init__.py", line 1110, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "I:\AI\Chart GLM\main\wenda\WPy64-31110\python-3.11.1.amd64\Lib\logging\__init__.py", line 953, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "I:\AI\Chart GLM\main\wenda\WPy64-31110\python-3.11.1.amd64\Lib\logging\__init__.py", line 687, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "I:\AI\Chart GLM\main\wenda\WPy64-31110\python-3.11.1.amd64\Lib\logging\__init__.py", line 377, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: not all arguments converted during string formatting
Call stack:
  File "I:\AI\Chart GLM\main\wenda\WPy64-31110\python-3.11.1.amd64\Lib\threading.py", line 995, in _bootstrap
    self._bootstrap_inner()
  File "I:\AI\Chart GLM\main\wenda\WPy64-31110\python-3.11.1.amd64\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "I:\AI\Chart GLM\main\wenda\WPy64-31110\python-3.11.1.amd64\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "I:\AI\Chart GLM\main\wenda\wenda.py", line 53, in load_model
    LLM.load_model()
  File "I:\AI\Chart GLM\main\wenda\llms\llm_glm6b.py", line 70, in load_model
    model = AutoModel.from_pretrained(
  File "I:\AI\Chart GLM\main\wenda\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\transformers\models\auto\auto_factory.py", line 479, in from_pretrained
    return model_class.from_pretrained(
  File "I:\AI\Chart GLM\main\wenda\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\transformers\modeling_utils.py", line 2675, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "C:\Users\wu5shen/.cache\huggingface\modules\transformers_modules\chatglm-6b-int4\modeling_chatglm.py", line 1061, in __init__
    self.quantize(self.config.quantization_bit, self.config.quantization_embeddings, use_quantization_cache=True, empty_init=True)
  File "C:\Users\wu5shen/.cache\huggingface\modules\transformers_modules\chatglm-6b-int4\modeling_chatglm.py", line 1424, in quantize
    from .quantization import quantize, QuantizedEmbedding, QuantizedLinear, load_cpu_kernel
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\wu5shen/.cache\huggingface\modules\transformers_modules\chatglm-6b-int4\quantization.py", line 46, in <module>
    logger.warning("Failed to load cpm_kernels:", exception)
Message: 'Failed to load cpm_kernels:'
Arguments: (NotADirectoryError(20, '目录名称无效。'),)
No compiled kernel found.
Compiling kernels : C:\Users\wu5shen\.cache\huggingface\modules\transformers_modules\chatglm-6b-int4\quantization_kernels_parallel.c
Compiling gcc -O3 -fPIC -pthread -fopenmp -std=c99 C:\Users\wu5shen\.cache\huggingface\modules\transformers_modules\chatglm-6b-int4\quantization_kernels_parallel.c -shared -o C:\Users\wu5shen\.cache\huggingface\modules\transformers_modules\chatglm-6b-int4\quantization_kernels_parallel.so
gcc: fatal error: cannot read spec file 'libgomp.spec': No such file or directory
compilation terminated.
Compile default cpu kernel failed, using default cpu kernel code.
Compiling gcc -O3 -fPIC -std=c99 C:\Users\wu5shen\.cache\huggingface\modules\transformers_modules\chatglm-6b-int4\quantization_kernels.c -shared -o C:\Users\wu5shen\.cache\huggingface\modules\transformers_modules\chatglm-6b-int4\quantization_kernels.so
Load kernel : C:\Users\wu5shen\.cache\huggingface\modules\transformers_modules\chatglm-6b-int4\quantization_kernels.so
Using quantization cache
Applying quantization to glm layers
模型加载完成
127.0.0.1:你好
错误 'NoneType' object has no attribute 'int4WeightExtractionHalf'

**Comment by JohnHsiao1** [comment]
同求 同求

**Comment by l15y** [comment]
重新下模型

**Comment by wu5shen** [comment]
重下的新模型也还是这样的
检测到集成环境
Namespace(Config='config.yml', Port=None, Logging=None, LLM_Type='glm6b')
library:
  count: 5
  step: 2
  strategy: calc:2 rtst:2 agents:0
librarys:
  bing:
    count: 5
  bingsite:
    count: 5
    site: www.12371.cn
  fess:
    count: 1
    fess_host: 127.0.0.1:8080
  kg:
    count: 5
    graph_host: ''
    knowledge_path: ''
    model_path: ''
  qdrant:
    batch_size: 32
    collection: qa_collection
    count: 3
    device: cpu
    model_path: model/m3e-base
    overlap: 0
    path: txt
    qdrant_path: memory/q
    similarity_threshold: 0.8
    size: 20
  remote:
    host: http://127.0.0.1:17860/api/find
  rtst:
    count: 3
    device: cuda
    model_path: model/m3e-base
    overlap: 0
    size: 20
llm:
  path: model\chatglm2-6b-int4
  strategy: cuda fp16
llm_type: glm6b
logging: false
port: 17860

[['cuda', 'fp16']]
Failed to load cpm_kernels:[WinError 267] 目录名称无效。: 'C:\\Users\\wu5shen\\AppData\\Local\\Programs\\Python\\Python310\\python.exe'
'gcc' is not recognized as an internal or external command,
operable program or batch file.
Compile parallel cpu kernel gcc -O3 -fPIC -pthread -fopenmp -std=c99 C:\Users\wu5shen\.cache\huggingface\modules\transformers_modules\chatglm2-6b-int4\quantization_kernels_parallel.c -shared -o C:\Users\wu5shen\.cache\huggingface\modules\transformers_modules\chatglm2-6b-int4\quantization_kernels_parallel.so failed.
'gcc' is not recognized as an internal or external command,
operable program or batch file.
Compile cpu kernel gcc -O3 -fPIC -std=c99 C:\Users\wu5shen\.cache\huggingface\modules\transformers_modules\chatglm2-6b-int4\quantization_kernels.c -shared -o C:\Users\wu5shen\.cache\huggingface\modules\transformers_modules\chatglm2-6b-int4\quantization_kernels.so failed.
模型加载完成
No sentence-transformers model found with name model/m3e-base. Creating a new one with MEAN pooling.
知识库加载完成
127.0.0.1:你好
错误 'NoneType' object has no attribute 'int4WeightExtractionHalf'

**Comment by l15y** [comment]
目录名称无效。: 'C:\Users\wu5shen\AppData\Local\Programs\Python\Python310\python.exe'

**Comment by wu5shen** [comment]
这是我电脑本地的python地址啊，是正常安装的，文件也在，而且这个不是整合包吗，不应该和我自己安装的python没关系吗
