### ISSUE TITLE
把知识库打开后，就不回答问题了。

### ISSUE THREAD

**Issue by heiheiheibj** [wenda-LLM/wenda#435]
[['cuda', 'fp16']]
Loading checkpoint shards:   0%|                                                                 | 0/7 [00:00<?, ?it/s]embedding加载失败，请下载语义知识库计算模型
查看： https://github.com/l15y/wenda#st%E6%A8%A1%E5%BC%8F
知识库加载失败，请阅读说明
查看： https://github.com/l15y/wenda#%E7%9F%A5%E8%AF%86%E5%BA%93
Exception in thread Thread-2 (load_zsk):
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\6b\lib\site-packages\huggingface_hub\utils\_errors.py", line 261, in hf_raise_for_status
    response.raise_for_status()
  File "C:\ProgramData\anaconda3\envs\6b\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/api/models/model/m3e-base

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\6b\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\anaconda3\envs\6b\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\wenda\wenda\wenda.py", line 74, in load_zsk
    raise e
  File "C:\wenda\wenda\wenda.py", line 67, in load_zsk
    import plugins.zhishiku as zsk
  File "C:\wenda\wenda\plugins\zhishiku.py", line 15, in <module>
    zhishiku = import_module('plugins.zhishiku_'+item[0])
  File "C:\ProgramData\anaconda3\envs\6b\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\wenda\wenda\plugins\zhishiku_rtst.py", line 81, in <module>
    raise e
  File "C:\wenda\wenda\plugins\zhishiku_rtst.py", line 77, in <module>
    embeddings.client = sentence_transformers.SentenceTransformer(cunnrent_setting.model_path,
  File "C:\ProgramData\anaconda3\envs\6b\lib\site-packages\sentence_transformers\SentenceTransformer.py", line 87, in __init__
    snapshot_download(model_name_or_path,
  File "C:\ProgramData\anaconda3\envs\6b\lib\site-packages\sentence_transformers\util.py", line 442, in snapshot_download
    model_info = _api.model_info(repo_id=repo_id, revision=revision, token=token)
  File "C:\ProgramData\anaconda3\envs\6b\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\ProgramData\anaconda3\envs\6b\lib\site-packages\huggingface_hub\hf_api.py", line 1678, in model_info
    hf_raise_for_status(r)
  File "C:\ProgramData\anaconda3\envs\6b\lib\site-packages\huggingface_hub\utils\_errors.py", line 293, in hf_raise_for_status
    raise RepositoryNotFoundError(message, response) from e
huggingface_hub.utils._errors.RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-64ad87d5-7b9e55985de43bc754213588;6ca4999d-c0ce-4d9f-86d2-48a9f5101a57)

Repository Not Found for url: https://huggingface.co/api/models/model/m3e-base.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
Invalid username or password.
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 7/7 [00:23<00:00,  3.33s/it]
模型加载完成

到这里就停住了，通过浏览器可以打开http://127.0.0.1:17860/index.html
但是只能和模型本身对话，把知识库打开后，就不回答问题了。
比如在关闭知识库时，问“洛阳西汉壁画墓发掘报告说了什么”，还能回答一番。如果开启了知识库，就不响应了

**Comment by heiheiheibj** [comment]
![微信截图_20230712005749](https://github.com/wenda-LLM/wenda/assets/6910198/175bfb45-5269-45bf-a3e9-8013caca9394)

**Comment by l15y** [comment]
报错写的很明白了，去下

**Comment by heiheiheibj** [comment]
兄弟呀，我当时就试过 ，https://[huggingface.co/api/models/model/m3e-base 地址无效滴
