### ISSUE TITLE
embedding加载失败,查看:https://github.com/115y/wenda#st%E6%A8%A1%E5%BC

### ISSUE THREAD

**Issue by heiheiheibj** [wenda-LLM/wenda#444]
embedding加载失败，请下载相应模型
查看： https://github.com/l15y/wenda#st%E6%A8%A1%E5%BC%8F
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\6b\lib\site-packages\huggingface_hub\utils\_errors.py", line 261, in hf_raise_for_status
    response.raise_for_status()
  File "C:\ProgramData\anaconda3\envs\6b\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/api/models/model/m3e-base

我看了下，https://huggingface.co/api/models/model/m3e-base 这个地址提示 {"error":"Repository not found"}
这个库不存在？

**Comment by heiheiheibj** [comment]
确实模型地址变了，新的是 https://huggingface.co/moka-ai/m3e-base
手动下载后，放到model目录就可以了。
