### ISSUE TITLE
llama2无法调用

### ISSUE THREAD

**Issue by Hughhuh** [wenda-LLM/wenda#452]
Exception in thread Thread-1 (load_model):
Traceback (most recent call last):
  File "D:\BaiduNetdiskDownload\wenda\wenda\wenda\WPy64-31110\python-3.11.1.amd64\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "D:\BaiduNetdiskDownload\wenda\wenda\wenda\WPy64-31110\python-3.11.1.amd64\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "D:\BaiduNetdiskDownload\wenda\wenda\wenda\wenda\wenda.py", line 53, in load_model
    LLM.load_model()
  File "D:\BaiduNetdiskDownload\wenda\wenda\wenda\wenda\llms\llm_llama.py", line 295, in load_model
    tokenizer = AutoTokenizer.from_pretrained(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\BaiduNetdiskDownload\wenda\wenda\wenda\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\transformers\models\auto\tokenization_auto.py", line 655, in from_pretrained
    raise ValueError(
ValueError: Tokenizer class LlamaTokenizer does not exist or is not currently imported.
No sentence-transformers model found with name model/m3e-base. Creating a new one with MEAN pooling.

**Comment by linuxdevopscn** [comment]
卸载Transformers 安装最新的
pip uninstall Transformers
pip install Transformers

**Comment by Hughhuh** [comment]
我用的是懒人包，直接用最新的就行了吗

**Comment by l15y** [comment]
更新可解
