### ISSUE TITLE
centos系统运行gen_data_st.py时报错

### ISSUE THREAD

**Issue by uchihayou** [wenda-LLM/wenda#495]
centos运行python3 plugins/gen_data_st.py时，出现以下错误，请问大佬们这个是什么问题
-----------------------------------------------------------------------------------------------------------------------------------------
Embedding 加载完成
文件列表生成完成 1
处理进度 100 %
处理完成
新建索引
Traceback (most recent call last):
  File "/opt/wenda/wenda/plugins/gen_data_st.py", line 159, in <module>
    vectorstore_old = Vectorstore.load_local(
  File "/opt/python3/lib/python3.9/site-packages/langchain/vectorstores/faiss.py", line 449, in load_local
    index = faiss.read_index(
  File "/opt/python3/lib/python3.9/site-packages/faiss/swigfaiss.py", line 10206, in read_index
    return _swigfaiss.read_index(*args)
RuntimeError: Error in faiss::FileIOReader::FileIOReader(const char*) at /project/faiss/faiss/impl/io.cpp:67: Error: 'f' failed: could not open memory/default/index.faiss for reading: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/wenda/wenda/plugins/gen_data_st.py", line 166, in <module>
    vectorstore.save_local('memory/default')
AttributeError: 'NoneType' object has no attribute 'save_local'

**Comment by Midnight-719** [comment]
![image](https://github.com/wenda-LLM/wenda/assets/69374118/c590ce11-d3fc-4d26-907b-2d5d0785d54f)
不是faiss
