### ISSUE TITLE
报错 Too many open files

### ISSUE THREAD

**Issue by xiaohui0225** [wenda-LLM/wenda#516]
使用wenda写文章时出现以下报错：
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/wenda/lib/python3.11/asyncio/selector_events.py", line 165, in _accept_connection
    conn, addr = sock.accept()
                 ^^^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/wenda/lib/python3.11/socket.py", line 294, in accept
    fd, addr = self._accept()
               ^^^^^^^^^^^^^^
OSError: [Errno 24] Too many open files
socket.accept() out of system resource
socket: <asyncio.TransportSocket fd=8, family=2, type=1, proto=6, laddr=('0.0.0.0', 17860)>
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/wenda/lib/python3.11/asyncio/selector_events.py", line 165, in _accept_connection
    conn, addr = sock.accept()
                 ^^^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/wenda/lib/python3.11/socket.py", line 294, in accept
    fd, addr = self._accept()
               ^^^^^^^^^^^^^^
OSError: [Errno 24] Too many open files
socket.accept() out of system resource
socket: <asyncio.TransportSocket fd=8, family=2, type=1, proto=6, laddr=('0.0.0.0', 17860)>
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/wenda/lib/python3.11/asyncio/selector_events.py", line 165, in _accept_connection
    conn, addr = sock.accept()
                 ^^^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/wenda/lib/python3.11/socket.py", line 294, in accept
    fd, addr = self._accept()
               ^^^^^^^^^^^^^^
OSError: [Errno 24] Too many open files
socket.accept() out of system resource
socket: <asyncio.TransportSocket fd=8, family=2, type=1, proto=6, laddr=('0.0.0.0', 17860)>
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/wenda/lib/python3.11/asyncio/selector_events.py", line 165, in _accept_connection
    conn, addr = sock.accept()
                 ^^^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/wenda/lib/python3.11/socket.py", line 294, in accept
    fd, addr = self._accept()
               ^^^^^^^^^^^^^^
OSError: [Errno 24] Too many open files
socket.accept() out of system resource

**Comment by ImmNaruto** [comment]
linux有最大打开文件数限制，改一下就好了
