### ISSUE TITLE
构建知识库报错python plugins/gen_data_st.py时候ModuleNotFoundError: No module named 'exceptions'

### ISSUE THREAD

**Issue by hopeforus** [wenda-LLM/wenda#517]
python plugins/gen_data_st.py
Traceback (most recent call last):
  File "/home/hope/work/wenda/plugins/gen_data_st.py", line 12, in <module>
    import docx
  File "/home/hope/miniconda3/envs/wenda/lib/python3.10/site-packages/docx.py", line 30, in <module>
    from exceptions import PendingDeprecationWarning
ModuleNotFoundError: No module named 'exceptions'

**Comment by ImmNaruto** [comment]
要安装一下Python-docx库，pip install python-docx
