### ISSUE TITLE
错误name 'model' is not defined

### ISSUE THREAD

**Issue by Adolph3671** [wenda-LLM/wenda#527]
描述錯誤
chatglm3_mode True
[['cuda', 'fp16']]
Exception in thread Thread-1 (load_model):
Traceback (most recent call last):
  File "C:\wenda\WPy64-31110\python-3.11.1.amd64\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\wenda\WPy64-31110\python-3.11.1.amd64\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\wenda\wenda\wenda.py", line 53, in load_model
    LLM.load_model()
  File "C:\wenda\wenda\llms\llm_glm6b.py", line 102, in load_model
    tokenizer = AutoTokenizer.from_pretrained(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\wenda\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\transformers\models\auto\tokenization_auto.py", line 643, in from_pretrained
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\wenda\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\transformers\models\auto\tokenization_auto.py", line 487, in get_tokenizer_config
    resolved_config_file = cached_file(
                           ^^^^^^^^^^^^
  File "C:\wenda\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\transformers\utils\hub.py", line 417, in cached_file
    resolved_file = hf_hub_download(
                    ^^^^^^^^^^^^^^^^
  File "C:\wenda\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\huggingface_hub\utils\_validators.py", line 112, in _inner_fn
    validate_repo_id(arg_value)
  File "C:\wenda\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\huggingface_hub\utils\_validators.py", line 166, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: 'model\chatglm3-6b'.
No sentence-transformers model found with name model/m3e-base. Creating a new one with MEAN pooling.
重現
重現該行為的步驟：
聞達"啟動器達啟動器''
點選 '運行服務GLM6B'

螢幕截圖
![螢幕擷取畫面 2024-03-28 163318](https://github.com/wenda-LLM/wenda/assets/68988733/87a607c9-f452-414c-9664-b9a5edc7bf64)

作業系統：[Win11]

**Comment by sxyseo** [comment]
需要修改配置文件或者下载chatglm3-6b到wenda\model文件夹下
